import { colors } from './theme';
import { computeAge } from './petAge';
import { daysAway, formatDate as formatDueDate } from './vaccineDisplay';
import { ReportKeyValue } from './pdfReport';
import {
  Dog,
  Profile,
  DogMood,
  MealDetail,
  HealthLog,
  VaccineRecord,
  PoopConsistency,
  PoopColor,
  VomitSeverity,
  VomitCause,
} from '../types';
import {
  MOOD_LABEL,
  MOOD_EMOJI,
  MOOD_COLOR,
  formatLongDate as formatMoodDate,
  formatWeekday,
} from '../screens/MoodHistoryScreen';
import {
  FOOD_TYPE_LABEL,
  dateKey as mealDateKey,
  formatTime as formatMealTime,
  mealNameFor,
  amountPillsFor,
  formatBrands,
  mostCommon,
  totalGrams,
  formatLongDate as formatMealDate,
} from '../screens/MealHistoryScreen';
import {
  CONSISTENCY_LABEL,
  SEVERITY_LABEL,
  CAUSE_LABEL,
  formatLongDate as formatSymptomDate,
  dateKey as symptomDateKey,
  formatTime as formatSymptomTime,
} from '../screens/SymptomHistoryScreen';

export type ReportSection = {
  heading: string;
  tableHeaders: string[];
  tableRowsHtml: string;
  summaryRows: ReportKeyValue[];
};

export type ReportBuild = ReportSection & {
  filename: string;
  title: string;
};

function exportedLabel(formatDate: (d: string) => string): string {
  const today = new Date().toISOString().split('T')[0];
  return `${formatDate(today)} · PawCare app`;
}

const EXPORTED_KEY = 'Exported:';

export function buildDogInfoRows(dog: Dog, profile: Profile | null): ReportKeyValue[] {
  const sexLabel = dog.sex === 'male' ? 'Male' : dog.sex === 'female' ? 'Female' : 'Unknown';
  const ageLabel = computeAge(dog.birth_date) || 'Unknown';
  const weightLabel = dog.weight_kg != null ? `${dog.weight_kg} kg` : 'Unknown';
  const ownerLabel = `${profile?.full_name ?? 'Unknown'}${profile?.username ? ` (@${profile.username})` : ''}`;
  return [
    { key: 'Dog name:', value: dog.name },
    { key: 'Breed:', value: `${dog.breed ?? 'Unknown'} · ${sexLabel}` },
    { key: 'Age / Weight:', value: `${ageLabel} · ${weightLabel}` },
    { key: 'Owner:', value: ownerLabel },
  ];
}

export function buildMoodReport(
  dog: Dog,
  historyByDate: Map<string, DogMood['mood']>
): ReportBuild | null {
  if (historyByDate.size === 0) return null;

  const entriesNewestFirst = Array.from(historyByDate.entries())
    .sort(([a], [b]) => b.localeCompare(a));
  const dates = entriesNewestFirst.map(([date]) => date);
  const newestDate = dates[0];
  const oldestDate = dates[dates.length - 1];

  const totalDaysInPeriod = Math.round(
    (new Date(newestDate).getTime() - new Date(oldestDate).getTime()) / 86400000
  ) + 1;

  const moodCounts = new Map<DogMood['mood'], number>();
  let concerningDays = 0;
  for (const [, mood] of entriesNewestFirst) {
    moodCounts.set(mood, (moodCounts.get(mood) ?? 0) + 1);
    if (mood === 'off' || mood === 'sick') concerningDays += 1;
  }
  let mostCommonMood: DogMood['mood'] | null = null;
  let mostCommonCount = 0;
  for (const [mood, count] of moodCounts) {
    if (count > mostCommonCount) { mostCommonMood = mood; mostCommonCount = count; }
  }

  const periodLabel = oldestDate === newestDate
    ? formatMoodDate(newestDate)
    : `${formatMoodDate(oldestDate)} – ${formatMoodDate(newestDate)}`;

  const tableRows = entriesNewestFirst.map(([date, mood], i) => `
    <tr style="background:${i % 2 === 1 ? '#F8FCF6' : '#FFFFFF'};">
      <td>${formatMoodDate(date)}</td>
      <td>${formatWeekday(date)}</td>
      <td style="color:${MOOD_COLOR[mood]};font-weight:600;">${MOOD_LABEL[mood]}</td>
      <td>${MOOD_EMOJI[mood]}</td>
    </tr>
  `).join('');

  const newest = new Date(newestDate);
  const monthAbbrev = newest.toLocaleDateString('en-US', { month: 'short' });

  return {
    heading: '🐾 Mood History',
    filename: `${dog.name.replace(/\s+/g, '_')}_mood_history_${monthAbbrev}${newest.getFullYear()}.pdf`,
    title: '🐾 PawCare — Mood History Report',
    tableHeaders: ['Date', 'Day', 'Mood', 'Emoji'],
    tableRowsHtml: tableRows,
    summaryRows: [
      { key: 'Most common mood:', value: mostCommonMood ? `${MOOD_LABEL[mostCommonMood]} (${mostCommonCount} days)` : '—' },
      { key: 'Days logged:', value: `${historyByDate.size} of ${totalDaysInPeriod} days` },
      { key: 'Concerning days:', value: `${concerningDays}` },
      { key: 'Period:', value: periodLabel },
      { key: EXPORTED_KEY, value: exportedLabel(formatMoodDate) },
      { key: 'Generated by:', value: 'PawCare · pawcare.app' },
    ],
  };
}

export function buildMealReport(dog: Dog, mealDetails: MealDetail[]): ReportBuild | null {
  if (mealDetails.length === 0) return null;

  const allSorted = mealDetails.slice().sort((a, b) => b.logged_at.localeCompare(a.logged_at));
  const newestDate = mealDateKey(allSorted[0].logged_at);
  const oldestDate = mealDateKey(allSorted[allSorted.length - 1].logged_at);

  const mostCommonType = mostCommon(mealDetails.map(d => d.food_type));
  const avgGramsPerMeal = Math.round(
    mealDetails.reduce((sum, d) => sum + totalGrams(d), 0) / mealDetails.length
  );

  const periodLabel = oldestDate === newestDate
    ? formatMealDate(newestDate)
    : `${formatMealDate(oldestDate)} – ${formatMealDate(newestDate)}`;

  const tableRows = allSorted.map((d, i) => {
    const amount = amountPillsFor(d).map(p => `${p.amount}g ${p.sub}`).join(', ') || '—';
    const brand = formatBrands(d).map(b => `${b.label}: ${b.brand}`).join(', ') || '—';
    return `
      <tr style="background:${i % 2 === 1 ? '#F8FCF6' : '#FFFFFF'};">
        <td>${formatMealDate(mealDateKey(d.logged_at))}</td>
        <td>${formatMealTime(d.logged_at)}</td>
        <td>${mealNameFor(d.logged_at)}</td>
        <td>${FOOD_TYPE_LABEL[d.food_type]}</td>
        <td>${amount}</td>
        <td>${brand}</td>
      </tr>
    `;
  }).join('');

  const newest = new Date(newestDate);
  const monthAbbrev = newest.toLocaleDateString('en-US', { month: 'short' });

  return {
    heading: '🍽️ Meal History',
    filename: `${dog.name.replace(/\s+/g, '_')}_meal_history_${monthAbbrev}${newest.getFullYear()}.pdf`,
    title: '🐾 PawCare — Meal History Report',
    tableHeaders: ['Date', 'Time', 'Meal', 'Type', 'Amount', 'Brand'],
    tableRowsHtml: tableRows,
    summaryRows: [
      { key: 'Total meals logged:', value: `${mealDetails.length}` },
      { key: 'Most common type:', value: mostCommonType ? FOOD_TYPE_LABEL[mostCommonType] : '—' },
      { key: 'Avg grams per meal:', value: `${avgGramsPerMeal}g` },
      { key: 'Period:', value: periodLabel },
      { key: EXPORTED_KEY, value: exportedLabel(formatMealDate) },
      { key: 'Generated by:', value: 'PawCare · pawcare.app' },
    ],
  };
}

export function buildSymptomReport(
  dog: Dog,
  logs: HealthLog[],
  vomitLogs: HealthLog[]
): ReportBuild | null {
  if (logs.length === 0 && vomitLogs.length === 0) return null;

  const entriesNewestFirst = [...logs, ...vomitLogs]
    .slice()
    .sort((a, b) => b.logged_at.localeCompare(a.logged_at));
  const newestDate = symptomDateKey(entriesNewestFirst[0].logged_at);
  const oldestDate = symptomDateKey(entriesNewestFirst[entriesNewestFirst.length - 1].logged_at);

  const consistencyCounts = new Map<PoopConsistency, number>();
  for (const l of logs) {
    const c = (l.details as { consistency: PoopConsistency }).consistency;
    consistencyCounts.set(c, (consistencyCounts.get(c) ?? 0) + 1);
  }
  let mostCommonConsistency: PoopConsistency | null = null;
  let mostCommonCount = 0;
  for (const [c, count] of consistencyCounts) {
    if (count > mostCommonCount) { mostCommonConsistency = c; mostCommonCount = count; }
  }

  const periodLabel = oldestDate === newestDate
    ? formatSymptomDate(newestDate)
    : `${formatSymptomDate(oldestDate)} – ${formatSymptomDate(newestDate)}`;

  const tableRows = entriesNewestFirst.map((l, i) => {
    const isPoop = l.type === 'poop';
    const typeColor = isPoop ? colors.pendingAmberText : colors.allergenText;
    const details = isPoop
      ? `${CONSISTENCY_LABEL[(l.details as { consistency: PoopConsistency }).consistency]} · ${(() => {
          const color = (l.details as { color: PoopColor }).color;
          return color[0].toUpperCase() + color.slice(1);
        })()}`
      : `${SEVERITY_LABEL[(l.details as { severity: VomitSeverity }).severity]} · ${CAUSE_LABEL[(l.details as { possibleCause: VomitCause }).possibleCause]}`;
    const frequency = (l.details as { frequency: number }).frequency;
    return `
      <tr style="background:${i % 2 === 1 ? '#F8FCF6' : '#FFFFFF'};">
        <td>${formatSymptomDate(symptomDateKey(l.logged_at))}</td>
        <td>${formatSymptomTime(l.logged_at)}</td>
        <td style="color:${typeColor};font-weight:600;">${isPoop ? 'Poop' : 'Vomit'}</td>
        <td>${details}</td>
        <td>${frequency}</td>
        <td>${l.notes ?? '—'}</td>
      </tr>
    `;
  }).join('');

  const newest = new Date(newestDate);
  const monthAbbrev = newest.toLocaleDateString('en-US', { month: 'short' });

  return {
    heading: '🩺 Symptom History',
    filename: `${dog.name.replace(/\s+/g, '_')}_symptom_history_${monthAbbrev}${newest.getFullYear()}.pdf`,
    title: '🐾 PawCare — Symptom History Report',
    tableHeaders: ['Date', 'Time', 'Type', 'Details', 'Frequency', 'Notes'],
    tableRowsHtml: tableRows,
    summaryRows: [
      { key: 'Poop logs:', value: `${logs.length}` },
      { key: 'Vomit logs:', value: `${vomitLogs.length}` },
      { key: 'Most common stool:', value: mostCommonConsistency ? CONSISTENCY_LABEL[mostCommonConsistency] : '—' },
      { key: 'Period:', value: periodLabel },
      { key: EXPORTED_KEY, value: exportedLabel(formatSymptomDate) },
      { key: 'Generated by:', value: 'PawCare · pawcare.app' },
    ],
  };
}

export function buildVaccineReport(
  dog: Dog,
  overdue: VaccineRecord[],
  upcoming: VaccineRecord[]
): ReportBuild | null {
  const allVaccines = [...overdue, ...upcoming];
  if (allVaccines.length === 0) return null;

  const statusFor = (v: VaccineRecord) => {
    const isOverdue = overdue.includes(v);
    const days = daysAway(v.next_due_date);
    if (isOverdue) return { label: 'Overdue', color: colors.allergenText };
    if (days <= 30) return { label: 'Soon', color: colors.pendingAmberText };
    return { label: 'Scheduled', color: colors.primaryGreen };
  };

  const tableRows = allVaccines.map((v, i) => {
    const status = statusFor(v);
    return `
      <tr style="background:${i % 2 === 1 ? '#F8FCF6' : '#FFFFFF'};">
        <td>${v.vaccine_name}</td>
        <td>${v.date_given ? formatDueDate(v.date_given) : '—'}</td>
        <td>${formatDueDate(v.next_due_date)}</td>
        <td style="color:${status.color};font-weight:600;">${status.label}</td>
        <td>${v.notes ?? '—'}</td>
      </tr>
    `;
  }).join('');

  const today = new Date();
  const monthAbbrev = today.toLocaleDateString('en-US', { month: 'short' });

  return {
    heading: '💉 Vaccine History',
    filename: `${dog.name.replace(/\s+/g, '_')}_vaccine_history_${monthAbbrev}${today.getFullYear()}.pdf`,
    title: '🐾 PawCare — Vaccine History Report',
    tableHeaders: ['Vaccine', 'Date Given', 'Next Due', 'Status', 'Notes'],
    tableRowsHtml: tableRows,
    summaryRows: [
      { key: 'Total tracked:', value: `${allVaccines.length}` },
      { key: 'Overdue:', value: `${overdue.length}` },
      { key: 'Upcoming (next 30 days):', value: `${allVaccines.filter(v => !overdue.includes(v) && daysAway(v.next_due_date) <= 30).length}` },
      { key: EXPORTED_KEY, value: exportedLabel(formatDueDate) },
      { key: 'Generated by:', value: 'PawCare · pawcare.app' },
    ],
  };
}
