export const colors = {
  background: '#F2F7EE',
  card: '#FFFFFF',
  cardBorder: '#D0E4C8',
  primaryGreen: '#3A7A1A',
  doneGreen: '#3A8A1A',
  pendingAmber: '#C47A1A',
  pendingAmberBg: '#FDF0DC',
  pendingAmberText: '#8A5A0A',
  notStartedBg: '#EDF0EA',
  notStartedText: '#5A6A50',
  allergenBg: '#FDE8E8',
  allergenText: '#8A1A1A',
  textMuted: '#5A6A50',
  moodSelectedBg: '#D4EBCC',
  moodSelectedBorder: '#3A7A1A',
  textDark: '#1A3A10',
  streakAccent: '#E08A2A',
  streakAccentBg: '#FDF0DC',
  communityBlueBg: '#E3EEFA',
  communityBlueText: '#2A5A9A',
  symptomBothBg: '#EEE0FF',
  symptomBothText: '#6A1A9A',
  alertCardBg: '#FFF8F8',
  alertBorder: '#E0A0A0',
} as const;

export const radii = {
  card: 14,
} as const;
